try{
    console.log(a)
}
catch(err){
console.log("caught an error a is not defined");
console.log(err);
}